"""add_total_assigned_hours_to_project

Revision ID: 038b774f910d
Revises: 842d6ad69233
Create Date: 2026-05-13 09:23:26.876734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '038b774f910d'
down_revision: Union[str, Sequence[str], None] = '842d6ad69233'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('total_assigned_hours', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'total_assigned_hours')
    # ### end Alembic commands ###
