"""add phone and emergency fields

Revision ID: 24facdb127b3
Revises: a6da66563981
Create Date: 2026-05-13 08:45:16.321792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24facdb127b3'
down_revision: Union[str, Sequence[str], None] = 'a6da66563981'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('users', sa.Column('emergency_contact_number', sa.String(), nullable=True))
    op.add_column('users', sa.Column('emergency_contact_relationship', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'emergency_contact_relationship')
    op.drop_column('users', 'emergency_contact_number')
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
