"""add project summary fields

Revision ID: 341b4b062dbd
Revises: fc97a07fc78a
Create Date: 2026-05-13 11:47:59.026572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '341b4b062dbd'
down_revision: Union[str, Sequence[str], None] = 'fc97a07fc78a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_assignments', sa.Column('base_pay', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('project_assignments', sa.Column('hourly_rate', sa.Numeric(precision=8, scale=2), nullable=True))
    op.add_column('projects', sa.Column('partner_hourly_rate', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('projects', sa.Column('billed_amount', sa.Numeric(precision=12, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'billed_amount')
    op.drop_column('projects', 'partner_hourly_rate')
    op.drop_column('project_assignments', 'hourly_rate')
    op.drop_column('project_assignments', 'base_pay')
    # ### end Alembic commands ###
