"""fix missing project dates and remuneration fields

Revision ID: 4e939cc7fd66
Revises: 000f00a1c2d0
Create Date: 2026-05-14 12:49:52.173263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e939cc7fd66'
down_revision: Union[str, Sequence[str], None] = '000f00a1c2d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('start_date', sa.Date(), nullable=True))
    op.add_column('projects', sa.Column('end_date', sa.Date(), nullable=True))
    op.add_column('projects', sa.Column('employee_budget', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('projects', sa.Column('partner_budget', sa.Numeric(precision=12, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'partner_budget')
    op.drop_column('projects', 'employee_budget')
    op.drop_column('projects', 'end_date')
    op.drop_column('projects', 'start_date')
    # ### end Alembic commands ###
