"""add remuneration fields

Revision ID: 626db617633d
Revises: 4f5d02fe5a64
Create Date: 2026-05-06 05:02:54.760031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '626db617633d'
down_revision: Union[str, Sequence[str], None] = '4f5d02fe5a64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('partner_remuneration', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('projects', sa.Column('employee_remuneration', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('projects', sa.Column('project_remuneration', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'project_remuneration')
    op.drop_column('projects', 'employee_remuneration')
    op.drop_column('projects', 'partner_remuneration')
    # ### end Alembic commands ###
