"""add tasks table

Revision ID: 6d2de6b93b58
Revises: bf9fdc432d5c
Create Date: 2026-05-11 04:34:59.976332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d2de6b93b58'
down_revision: Union[str, Sequence[str], None] = 'bf9fdc432d5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('duration_hours', sa.Integer(), nullable=True))
    op.drop_column('tasks', 'end_time')
    op.drop_column('tasks', 'start_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('start_time', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('end_time', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('tasks', 'duration_hours')
    # ### end Alembic commands ###
