"""Add WeeklyTimesheetEntry

Revision ID: 842d6ad69233
Revises: 24facdb127b3
Create Date: 2026-05-13 09:04:34.673633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '842d6ad69233'
down_revision: Union[str, Sequence[str], None] = '24facdb127b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weekly_timesheet_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timesheet_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('hours', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['timesheet_id'], ['weekly_timesheets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('weekly_timesheet_projects')
    op.alter_column('weekly_timesheets', 'total_hours',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=6, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('weekly_timesheets', 'total_hours',
               existing_type=sa.Numeric(precision=6, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.create_table('weekly_timesheet_projects',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('timesheet_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('weekly_timesheet_projects_project_id_fkey')),
    sa.ForeignKeyConstraint(['timesheet_id'], ['weekly_timesheets.id'], name=op.f('weekly_timesheet_projects_timesheet_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('weekly_timesheet_projects_pkey'))
    )
    op.drop_table('weekly_timesheet_entries')
    # ### end Alembic commands ###
