"""add document and workorder url fields

Revision ID: 87c2db9d6753
Revises: c7ce3821ed8a
Create Date: 2026-05-11 07:09:19.156327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87c2db9d6753'
down_revision: Union[str, Sequence[str], None] = 'c7ce3821ed8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('work_order_urls', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'work_order_urls')
    # ### end Alembic commands ###
