"""fix client phone to string

Revision ID: 8d1deaa4a6fa
Revises: a9c4dd98c219
Create Date: 2026-05-05 10:11:58.084040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d1deaa4a6fa'
down_revision: Union[str, Sequence[str], None] = 'a9c4dd98c219'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'project_assignments', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'project_assignments', 'projects', ['project_id'], ['id'])
    op.alter_column('projects', 'location',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('projects', 'gmap_link',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('projects', 'year',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('projects', 'current_stage',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'current_stage',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('projects', 'year',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('projects', 'gmap_link',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('projects', 'location',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'project_assignments', type_='foreignkey')
    op.drop_constraint(None, 'project_assignments', type_='foreignkey')
    # ### end Alembic commands ###
