"""add expenses table

Revision ID: 93c24801f857
Revises: 626db617633d
Create Date: 2026-05-06 10:30:30.471523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93c24801f857'
down_revision: Union[str, Sequence[str], None] = '626db617633d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('recurring', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('added_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('salary_hour', sa.Numeric(precision=8, scale=2), nullable=True))
    op.add_column('users', sa.Column('documents_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('time_tracker_login', sa.String(), nullable=True))
    op.add_column('users', sa.Column('time_tracker_password', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'time_tracker_password')
    op.drop_column('users', 'time_tracker_login')
    op.drop_column('users', 'documents_url')
    op.drop_column('users', 'salary_hour')
    op.drop_table('expenses')
    # ### end Alembic commands ###
