"""fix weekly timesheet model columns

Revision ID: a6da66563981
Revises: bec9f52a28e4
Create Date: 2026-05-13 08:26:25.613924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6da66563981'
down_revision: Union[str, Sequence[str], None] = 'bec9f52a28e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weekly_timesheets', sa.Column('description', sa.String(), nullable=True))
    op.add_column('weekly_timesheets', sa.Column('rejection_reason', sa.String(), nullable=True))
    op.alter_column('weekly_timesheets', 'total_hours',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('weekly_timesheets', 'rejection')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weekly_timesheets', sa.Column('rejection', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('weekly_timesheets', 'total_hours',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('weekly_timesheets', 'rejection_reason')
    op.drop_column('weekly_timesheets', 'description')
    # ### end Alembic commands ###
