"""add leave and attendance tables

Revision ID: d2fd1784f834
Revises: 93c24801f857
Create Date: 2026-05-11 04:04:10.184879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2fd1784f834'
down_revision: Union[str, Sequence[str], None] = '93c24801f857'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('check_in', sa.String(), nullable=True),
    sa.Column('check_out', sa.String(), nullable=True),
    sa.Column('is_site_visit', sa.Boolean(), nullable=True),
    sa.Column('site_name', sa.String(), nullable=True),
    sa.Column('site_timing', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attendance')
    # ### end Alembic commands ###
